### ISSUE TITLE
Parse not working correctly

### ISSUE THREAD

**Issue by astrocreep** [romgrk/color-bits#1]
Tried parsing some color values, but the results are wrong:

```
import { parse } from 'color-bits'

parse('#ABD7A6')
// expected 11261862
// got -1411930369

parse('#FFFFFF')
// expected 16777215
// got -1

```

**Comment by romgrk** [comment]
Not wrong, please read https://github.com/romgrk/color-bits#-technical-details and/or https://romgrk.com/posts/color-bits.

**Comment by romgrk** [comment]
You can use `toNumber` or any of the formatting functions to turn the values back in formats you can print.
